#!/bin/bash
# install and enable service on hosts
# DEPLOY					# update dispatch, signal (from pool) and service_update (from local) to all hosts
# DEPLOY <service>				# install <service> on all hosts
# DEPLOY <service> <host>			# install <service> on <host> 
# DEPLOY <service> <host1> <host2> <host3> ...  # install <service> on listed hosts

signal=10000
signal()  {
   host="$1"
   shift
   nc $host $signal <<< "$@"
}

hosts="cubie banana odroid radxa raspberry buffalo"
if [[ -z $1 ]]; then
   pool="/misc/buffalo"
   
   copy()  {
      printf ' %s' "${1##*/}"
      rsync -a "$1" "$2"
   }

   for h in $hosts; do

      printf '%s: ' "$h: syncing files"
      copy $pool/etc/xinetd.d/signal.handler/pool/signal   $h:/etc/xinetd.d
      copy $pool/etc/xinetd.d/signal.handler/pool/dispatch $h:/etc/xinetd.d/signal.handler
      copy /etc/xinetd.d/signal.handler/service_update     $h:/etc/xinetd.d/signal.handler
      printf '\n'

      echo "$h: xinetd restarting"
      ssh $h /etc/init.d/xinetd restart > /dev/null

      echo "$h: updating services"
      signal $h update force

   done
else
   service="$1"
   shift
   for h in $@; do
      signal $h install $service
      signal $h service $service 1
   done
fi
